import "dotenv/config";

import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL is not set");
}

const pool = new Pool({
  connectionString: databaseUrl,
});

const prisma = new PrismaClient({
  adapter: new PrismaPg(pool),
});

async function main() {
  // await prisma.city.createMany({
  //   data: [
  //     {
  //       id: "city_casablanca",
  //       name: "Casablanca",
  //       name_en: "Casablanca",
  //       name_ar: "الدار البيضاء",
  //       name_fr: "Casablanca",
  //       slug: "casablanca",
  //     },
  //     {
  //       id: "city_rabat",
  //       name: "Rabat",
  //       name_en: "Rabat",
  //       name_ar: "الرباط",
  //       name_fr: "Rabat",
  //       slug: "rabat",
  //     },
  //     {
  //       id: "city_marrakech",
  //       name: "Marrakech",
  //       name_en: "Marrakech",
  //       name_ar: "مراكش",
  //       name_fr: "Marrakech",
  //       slug: "marrakech",
  //     },
  //     {
  //       id: "city_fes",
  //       name: "Fes",
  //       name_en: "Fes",
  //       name_ar: "فاس",
  //       name_fr: "Fès",
  //       slug: "fes",
  //     },
  //     {
  //       id: "city_tangier",
  //       name: "Tangier",
  //       name_en: "Tangier",
  //       name_ar: "طنجة",
  //       name_fr: "Tanger",
  //       slug: "tangier",
  //     },
  //     {
  //       id: "city_agadir",
  //       name: "Agadir",
  //       name_en: "Agadir",
  //       name_ar: "أكادير",
  //       name_fr: "Agadir",
  //       slug: "agadir",
  //     },
  //     {
  //       id: "city_meknes",
  //       name: "Meknes",
  //       name_en: "Meknes",
  //       name_ar: "مكناس",
  //       name_fr: "Meknès",
  //       slug: "meknes",
  //     },
  //     {
  //       id: "city_oujda",
  //       name: "Oujda",
  //       name_en: "Oujda",
  //       name_ar: "وجدة",
  //       name_fr: "Oujda",
  //       slug: "oujda",
  //     },
  //     {
  //       id: "city_kenitra",
  //       name: "Kenitra",
  //       name_en: "Kenitra",
  //       name_ar: "القنيطرة",
  //       name_fr: "Kénitra",
  //       slug: "kenitra",
  //     },
  //     {
  //       id: "city_tetouan",
  //       name: "Tetouan",
  //       name_en: "Tetouan",
  //       name_ar: "تطوان",
  //       name_fr: "Tétouan",
  //       slug: "tetouan",
  //     },
  //     {
  //       id: "city_safi",
  //       name: "Safi",
  //       name_en: "Safi",
  //       name_ar: "آسفي",
  //       name_fr: "Safi",
  //       slug: "safi",
  //     },
  //     {
  //       id: "city_el_jadida",
  //       name: "El Jadida",
  //       name_en: "El Jadida",
  //       name_ar: "الجديدة",
  //       name_fr: "El Jadida",
  //       slug: "el-jadida",
  //     },
  //     {
  //       id: "city_nador",
  //       name: "Nador",
  //       name_en: "Nador",
  //       name_ar: "الناظور",
  //       name_fr: "Nador",
  //       slug: "nador",
  //     },
  //     {
  //       id: "city_beni_mellal",
  //       name: "Beni Mellal",
  //       name_en: "Beni Mellal",
  //       name_ar: "بني ملال",
  //       name_fr: "Béni Mellal",
  //       slug: "beni-mellal",
  //     },
  //     {
  //       id: "city_essaouira",
  //       name: "Essaouira",
  //       name_en: "Essaouira",
  //       name_ar: "الصويرة",
  //       name_fr: "Essaouira",
  //       slug: "essaouira",
  //     },
  //     {
  //       id: "city_khouribga",
  //       name: "Khouribga",
  //       name_en: "Khouribga",
  //       name_ar: "خريبكة",
  //       name_fr: "Khouribga",
  //       slug: "khouribga",
  //     },
  //     {
  //       id: "city_settat",
  //       name: "Settat",
  //       name_en: "Settat",
  //       name_ar: "سطات",
  //       name_fr: "Settat",
  //       slug: "settat",
  //     },
  //     {
  //       id: "city_taza",
  //       name: "Taza",
  //       name_en: "Taza",
  //       name_ar: "تازة",
  //       name_fr: "Taza",
  //       slug: "taza",
  //     },
  //     {
  //       id: "city_khemisset",
  //       name: "Khemisset",
  //       name_en: "Khemisset",
  //       name_ar: "الخميسات",
  //       name_fr: "Khémisset",
  //       slug: "khemisset",
  //     },
  //     {
  //       id: "city_larache",
  //       name: "Larache",
  //       name_en: "Larache",
  //       name_ar: "العرائش",
  //       name_fr: "Larache",
  //       slug: "larache",
  //     },
  //     {
  //       id: "city_khenifra",
  //       name: "Khenifra",
  //       name_en: "Khenifra",
  //       name_ar: "خنيفرة",
  //       name_fr: "Khénifra",
  //       slug: "khenifra",
  //     },
  //     {
  //       id: "city_berrechid",
  //       name: "Berrechid",
  //       name_en: "Berrechid",
  //       name_ar: "برشيد",
  //       name_fr: "Berrechid",
  //       slug: "berrechid",
  //     },
  //     {
  //       id: "city_guelmim",
  //       name: "Guelmim",
  //       name_en: "Guelmim",
  //       name_ar: "كلميم",
  //       name_fr: "Guelmim",
  //       slug: "guelmim",
  //     },
  //     {
  //       id: "city_ouarzazate",
  //       name: "Ouarzazate",
  //       name_en: "Ouarzazate",
  //       name_ar: "ورزازات",
  //       name_fr: "Ouarzazate",
  //       slug: "ouarzazate",
  //     },
  //     {
  //       id: "city_errachidia",
  //       name: "Errachidia",
  //       name_en: "Errachidia",
  //       name_ar: "الراشيدية",
  //       name_fr: "Errachidia",
  //       slug: "errachidia",
  //     },
  //     {
  //       id: "city_al_hoceima",
  //       name: "Al Hoceima",
  //       name_en: "Al Hoceima",
  //       name_ar: "الحسيمة",
  //       name_fr: "Al Hoceïma",
  //       slug: "al-hoceima",
  //     },
  //     {
  //       id: "city_tiznit",
  //       name: "Tiznit",
  //       name_en: "Tiznit",
  //       name_ar: "تيزنيت",
  //       name_fr: "Tiznit",
  //       slug: "tiznit",
  //     },
  //     {
  //       id: "city_mohammedia",
  //       name: "Mohammedia",
  //       name_en: "Mohammedia",
  //       name_ar: "المحمدية",
  //       name_fr: "Mohammedia",
  //       slug: "mohammedia",
  //     },
  //     {
  //       id: "city_temara",
  //       name: "Temara",
  //       name_en: "Temara",
  //       name_ar: "تمارة",
  //       name_fr: "Témara",
  //       slug: "temara",
  //     },
  //     {
  //       id: "city_sale",
  //       name: "Sale",
  //       name_en: "Sale",
  //       name_ar: "سلا",
  //       name_fr: "Salé",
  //       slug: "sale",
  //     },
  //     {
  //       id: "city_ifrane",
  //       name: "Ifrane",
  //       name_en: "Ifrane",
  //       name_ar: "إفران",
  //       name_fr: "Ifrane",
  //       slug: "ifrane",
  //     },
  //     {
  //       id: "city_azrou",
  //       name: "Azrou",
  //       name_en: "Azrou",
  //       name_ar: "أزرو",
  //       name_fr: "Azrou",
  //       slug: "azrou",
  //     },
  //     {
  //       id: "city_midelt",
  //       name: "Midelt",
  //       name_en: "Midelt",
  //       name_ar: "ميدلت",
  //       name_fr: "Midelt",
  //       slug: "midelt",
  //     },
  //     {
  //       id: "city_tinghir",
  //       name: "Tinghir",
  //       name_en: "Tinghir",
  //       name_ar: "تنغير",
  //       name_fr: "Tinghir",
  //       slug: "tinghir",
  //     },
  //     {
  //       id: "city_chefchaouen",
  //       name: "Chefchaouen",
  //       name_en: "Chefchaouen",
  //       name_ar: "شفشاون",
  //       name_fr: "Chefchaouen",
  //       slug: "chefchaouen",
  //     },
  //     {
  //       id: "city_taroudant",
  //       name: "Taroudant",
  //       name_en: "Taroudant",
  //       name_ar: "تارودانت",
  //       name_fr: "Taroudant",
  //       slug: "taroudant",
  //     },
  //     {
  //       id: "city_ouед_zem",
  //       name: "Oued Zem",
  //       name_en: "Oued Zem",
  //       name_ar: "واد زم",
  //       name_fr: "Oued Zem",
  //       slug: "oued-zem",
  //     },
  //     {
  //       id: "city_youssoufia",
  //       name: "Youssoufia",
  //       name_en: "Youssoufia",
  //       name_ar: "اليوسفية",
  //       name_fr: "Youssoufia",
  //       slug: "youssoufia",
  //     },
  //     {
  //       id: "city_azilal",
  //       name: "Azilal",
  //       name_en: "Azilal",
  //       name_ar: "أزيلال",
  //       name_fr: "Azilal",
  //       slug: "azilal",
  //     },
  //     {
  //       id: "city_fquih_ben_salah",
  //       name: "Fquih Ben Salah",
  //       name_en: "Fquih Ben Salah",
  //       name_ar: "الفقيه بن صالح",
  //       name_fr: "Fquih Ben Salah",
  //       slug: "fquih-ben-salah",
  //     },
  //     {
  //       id: "city_sidi_kacem",
  //       name: "Sidi Kacem",
  //       name_en: "Sidi Kacem",
  //       name_ar: "سيدي قاسم",
  //       name_fr: "Sidi Kacem",
  //       slug: "sidi-kacem",
  //     },
  //     {
  //       id: "city_souk_el_arba",
  //       name: "Souk El Arba",
  //       name_en: "Souk El Arba",
  //       name_ar: "سوق الأربعاء",
  //       name_fr: "Souk El Arba",
  //       slug: "souk-el-arba",
  //     },
  //     {
  //       id: "city_ben_guerir",
  //       name: "Ben Guerir",
  //       name_en: "Ben Guerir",
  //       name_ar: "بن جرير",
  //       name_fr: "Ben Guerir",
  //       slug: "ben-guerir",
  //     },
  //     {
  //       id: "city_taourirt",
  //       name: "Taourirt",
  //       name_en: "Taourirt",
  //       name_ar: "تاوريرت",
  //       name_fr: "Taourirt",
  //       slug: "taourirt",
  //     },
  //     {
  //       id: "city_dakhla",
  //       name: "Dakhla",
  //       name_en: "Dakhla",
  //       name_ar: "الداخلة",
  //       name_fr: "Dakhla",
  //       slug: "dakhla",
  //     },
  //     {
  //       id: "city_laayoune",
  //       name: "Laayoune",
  //       name_en: "Laayoune",
  //       name_ar: "العيون",
  //       name_fr: "Laâyoune",
  //       slug: "laayoune",
  //     },
  //     {
  //       id: "city_tan_tan",
  //       name: "Tan-Tan",
  //       name_en: "Tan-Tan",
  //       name_ar: "طانطان",
  //       name_fr: "Tan-Tan",
  //       slug: "tan-tan",
  //     },
  //     {
  //       id: "city_sidi_ifni",
  //       name: "Sidi Ifni",
  //       name_en: "Sidi Ifni",
  //       name_ar: "سيدي إفني",
  //       name_fr: "Sidi Ifni",
  //       slug: "sidi-ifni",
  //     },
  //     {
  //       id: "city_boulemane",
  //       name: "Boulemane",
  //       name_en: "Boulemane",
  //       name_ar: "بولمان",
  //       name_fr: "Boulemane",
  //       slug: "boulemane",
  //     },
  //     {
  //       id: "city_ain_attig",
  //       name: "Ain Attig",
  //       name_en: "Ain Attig",
  //       name_ar: "عين عتيق",
  //       name_fr: "Aïn Attig",
  //       slug: "ain-attig",
  //     },
  //   ],
  //   skipDuplicates: true,
  // });

  // await prisma.propertyType.createMany({
  //   data: [
  //     {
  //       name: "Apartment",
  //       name_en: "Apartment",
  //       name_ar: "شقة",
  //       name_fr: "Appartement",
  //       slug: "apartment",
  //     },
  //     {
  //       name: "Villa",
  //       name_en: "Villa",
  //       name_ar: "فيلا",
  //       name_fr: "Villa",
  //       slug: "villa",
  //     },
  //     {
  //       name: "House",
  //       name_en: "House",
  //       name_ar: "منزل",
  //       name_fr: "Maison",
  //       slug: "house",
  //     },
  //     {
  //       name: "Studio",
  //       name_en: "Studio",
  //       name_ar: "استوديو",
  //       name_fr: "Studio",
  //       slug: "studio",
  //     },
  //     {
  //       name: "Duplex",
  //       name_en: "Duplex",
  //       name_ar: "دوبلكس",
  //       name_fr: "Duplex",
  //       slug: "duplex",
  //     },
  //     {
  //       name: "Penthouse",
  //       name_en: "Penthouse",
  //       name_ar: "بنتهاوس",
  //       name_fr: "Penthouse",
  //       slug: "penthouse",
  //     },
  //     {
  //       name: "Office",
  //       name_en: "Office",
  //       name_ar: "مكتب",
  //       name_fr: "Bureau",
  //       slug: "office",
  //     },
  //     {
  //       name: "Shop",
  //       name_en: "Shop",
  //       name_ar: "محل تجاري",
  //       name_fr: "Magasin",
  //       slug: "shop",
  //     },
  //     {
  //       name: "Commercial Space",
  //       name_en: "Commercial Space",
  //       name_ar: "مساحة تجارية",
  //       name_fr: "Local commercial",
  //       slug: "commercial-space",
  //     },
  //     {
  //       name: "Warehouse",
  //       name_en: "Warehouse",
  //       name_ar: "مستودع",
  //       name_fr: "Entrepôt",
  //       slug: "warehouse",
  //     },

  //     {
  //       name: "Building",
  //       name_en: "Building",
  //       name_ar: "عمارة",
  //       name_fr: "Immeuble",
  //       slug: "building",
  //     },
  //     {
  //       name: "Room",
  //       name_en: "Room",
  //       name_ar: "غرفة",
  //       name_fr: "Chambre",
  //       slug: "room",
  //     },
  //     {
  //       name: "Shared Accommodation",
  //       name_en: "Shared Accommodation",
  //       name_ar: "سكن مشترك",
  //       name_fr: "Colocation",
  //       slug: "shared-accommodation",
  //     },
  //   ],
  //   skipDuplicates: true,
  // });

  // await prisma.purchaseProduct.createMany({
  //   data: [
  //     {
  //       code: "EXTRA_IMAGES",
  //       title: "Extra Images",
  //       title_ar: "صور إضافية",
  //       title_fr: "Images supplémentaires",
  //       description: "Add extra images to a listing",
  //       price: 5,
  //       active: true,
  //     },
  //     {
  //       code: "ADS_DURATION_PER_DAY",
  //       title: "Ads Duration Per Day",
  //       title_ar: "مدة الإعلان اليومية",
  //       title_fr: "Durée quotidienne de l'annonce",
  //       description: "Extend advertisement duration by one day",
  //       price: 5,
  //       active: true,
  //     },
  //     {
  //       code: "EXTRA_VIDEOS",
  //       title: "Extra Videos",
  //       title_ar: "مقاطع فيديو إضافية",
  //       title_fr: "Vidéos supplémentaires",
  //       description: "Add extra videos to a listing",
  //       price: 10,
  //       active: true,
  //     },
  //     {
  //       code: "EXTRA_LISTINGS",
  //       title: "Extra Listings",
  //       title_ar: "عقارات إضافية",
  //       title_fr: "Annonces supplémentaires",
  //       description: "Increase the number of listings allowed",
  //       price: 25,
  //       active: true,
  //     },
  //     {
  //       code: "EXTRA_FEATURED_LISTINGS",
  //       title: "Extra Featured Listings",
  //       title_ar: "عقارات مميزة إضافية",
  //       title_fr: "Annonces mises en avant supplémentaires",
  //       description: "Add more featured listing slots",
  //       price: 20,
  //       active: true,
  //     },
  //   ],
  //   skipDuplicates: true,
  // });

  await prisma.plan.createMany({
    data: [
      {
        id: "plan_free",
        title: "Free",
        title_ar: "مجاني",
        title_fr: "Gratuit",
        description: "Get started with basic listings",
        description_ar: "ابدأ بالإعلانات الأساسية",
        description_fr: "Commencez avec des annonces de base",
        price: 0,
        listings: 3,
        featured: false,
        ads: 0,
        adsduration: 0,
        maxFeaturedListings: 0,
        maxImagesPerListing: 3,
        maxVideosPerListing: 0,
      },
      {
        id: "plan_pro",
        title: "Pro",
        title_ar: "احترافي",
        title_fr: "Pro",
        description: "Perfect for active sellers",
        description_ar: "مثالي للبائعين النشطين",
        description_fr: "Parfait pour les vendeurs actifs",
        price: 99,
        listings: 10,
        featured: true,
        ads: 5,
        adsduration: 10,
        maxFeaturedListings: 3,
        maxImagesPerListing: 10,
        maxVideosPerListing: 2,
      },
      {
        id: "plan_premium",
        title: "Premium",
        title_ar: "بريميوم",
        title_fr: "Premium",
        description: "Unlimited power for professionals",
        description_ar: "قدرة غير محدودة للمحترفين",
        description_fr: "Puissance illimitée pour les professionnels",
        price: 299,
        listings: null,
        featured: true,
        ads: 20,
        adsduration: 30,
        maxFeaturedListings: 10,
        maxImagesPerListing: 30,
        maxVideosPerListing: 5,
      },
    ],
    skipDuplicates: true,
  });
  console.log("✅ Seed completed successfully");
}
main()
  .catch((error) => {
    console.error("❌ Seed failed:");
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
